"""Second-node Expectation Trace patch for issue-driven simulations.

This module is intentionally small and measurement-only. It does not change
Hermes-Agent planning, tool dispatch, or provider behavior. It wraps issue
inputs and observed node outcomes into bounded expected-vs-actual transition
records for comparison with baseline diagnostics.
"""

from __future__ import annotations

from dataclasses import dataclass, asdict
from typing import Any


SURPRISE_WEIGHTS = {
    "auth_missing": 0.86,
    "provider_misconfigured": 0.82,
    "tool_unavailable": 0.78,
    "empty_output": 0.74,
    "malformed_output": 0.76,
    "context_mismatch": 0.70,
    "secret_leak_risk": 0.80,
    "platform_error": 0.72,
    "unknown": 0.55,
}


@dataclass
class IssueTransition:
    issue_number: str
    issue_title: str
    category: str
    expected_after: str
    actual_after: str
    recovery_hint: str
    action_name: str
    action_type: str = "issue_simulation_step"
    duration_ms: int = 1
    secret_redaction_ok: bool = True

    def surprise_score(self) -> float:
        base = SURPRISE_WEIGHTS.get(self.category, SURPRISE_WEIGHTS["unknown"])
        if self.actual_after.strip().lower() == self.expected_after.strip().lower():
            return 0.12
        if "clear" in self.actual_after.lower() or "bounded" in self.actual_after.lower():
            return round(max(0.18, base - 0.22), 2)
        return round(base, 2)

    def surprise_level(self) -> str:
        score = self.surprise_score()
        if score >= 0.67:
            return "high"
        if score >= 0.34:
            return "medium"
        return "low"

    def to_trace(self, trace_id: str, run_id: str, task_id: str, timestamp: str) -> dict[str, Any]:
        return {
            "trace_id": trace_id,
            "run_id": run_id,
            "task_id": task_id,
            "sandbox": "expectation_trace",
            "timestamp": timestamp,
            "goal": f"Evaluate fixture from Hermes-Agent issue #{self.issue_number}: {self.issue_title}",
            "state_before_summary": "Issue input loaded; expected postcondition extracted from issue or linked PR evidence.",
            "action": {
                "type": self.action_type,
                "name": self.action_name,
                "args_summary": f"issue=#{self.issue_number}; category={self.category}; bounded issue fixture",
            },
            "expected_after": self.expected_after,
            "actual_after": self.actual_after,
            "surprise_score": self.surprise_score(),
            "surprise_level": self.surprise_level(),
            "success": self.surprise_score() < 0.67,
            "error_category": self.category,
            "recovery_hint": self.recovery_hint,
            "duration_ms": self.duration_ms,
            "secret_redaction_ok": self.secret_redaction_ok,
            "notes": "Generated by the patched second-node observer from a fixed issue input.",
        }

    def as_patch_record(self) -> dict[str, Any]:
        record = asdict(self)
        record["surprise_score"] = self.surprise_score()
        record["surprise_level"] = self.surprise_level()
        return record
